name: CI

env:
  DENO_VERSION: 1.7.5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cli:
    name: Test CLI
    runs-on: ubuntu-latest

    steps:
      - name: Install deno
        uses: denolib/setup-deno@master
        with: 
          deno-version: ${{env.DENO_VERSION}}
          
      - name: Nessie Init
        run: deno run --allow-read --allow-write --allow-net --unstable https://raw.githubusercontent.com/$URL_PATH/cli.ts init
        env:
          URL_PATH: ${{github.event.pull_request.head.repo.full_name||github.repository}}/${{github.event.pull_request.head.ref||'main'}}

      - name: Create migration
        run: deno run --allow-read --allow-write --allow-net --unstable https://raw.githubusercontent.com/$URL_PATH/cli.ts make test
        env:
          URL_PATH: ${{github.event.pull_request.head.repo.full_name||github.repository}}/${{github.event.pull_request.head.ref||'main'}}

      - name: Create seed
        run: deno run --allow-read --allow-write --allow-net --unstable https://raw.githubusercontent.com/$URL_PATH/cli.ts make:seed test
        env:
          URL_PATH: ${{github.event.pull_request.head.repo.full_name||github.repository}}/${{github.event.pull_request.head.ref||'main'}}

  cli-migrations:
    name: Test CLI Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master
        with: 
          deno-version: ${{env.DENO_VERSION}}

      - name: Create databases
        run: make db-all-start

      - name: Run tests
        run: make test-cli-migrations

  cli-migrations-experimental:
    name: Test CLI Migrations Experimental
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{env.DENO_VERSION}}

      - name: Create databases
        run: make db-all-start

      - name: Run tests
        run: make test-cli-migrations-experimental
  
  cli-update-timestamps:
    name: Test CLI Update timestamps
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{env.DENO_VERSION}}

      - name: Run tests
        run: make test-cli-update-timestamps
