name: Publish Egg

env:
  DENO_VERSION: 1.24.1
  NEST_VERSION: 0.3.10

on:
  release:
    types: [published]

jobs:
  publish-egg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{env.DENO_VERSION}}

      - name: Publish module
        run: |
          deno run -A --unstable https://x.nest.land/eggs@${{env.NEST_VERSION}}/eggs.ts link ${{ secrets.NESTAPIKEY }}
          deno run -A --unstable https://x.nest.land/eggs@${{env.NEST_VERSION}}/eggs.ts publish -Y
